### ISSUE TITLE
下载运行报错，应该缺了文件

### ISSUE THREAD

**Issue by CNBlackJ** [ACOTeam/aircode-node#18]
```
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/5e88fa3a-ee4f-48b7-8fae-aa9c6454e99d
module.js:472
    throw err;
    ^

Error: Cannot find module './query'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jarvin/bnews/bnews-server-node/src/graphql/schema.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by CNBlackJ** [comment]
fixed
